"""add votes table autogenerated

Revision ID: 8258d53b16eb
Revises: 6a9740eb0297
Create Date: 2022-05-27 13:43:34.130131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8258d53b16eb'
down_revision = '6a9740eb0297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
